"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, CalendarDays, Database } from "lucide-react";
import { StatusPill } from "@/components/ui/status-pill";
import { loadDemoTrades } from "@/features/journal/data/demo-trade-store";
import { ReportMetric } from "@/features/reports/components/report-metric";
import { calculatePerformanceMetrics } from "@/lib/core/performance-service";
import { buildDailyReport, buildMonthlyReport, currentMonthKey, listAvailableDateKeys, localDateKey } from "@/lib/core/report-service";
import type { TradeRecord } from "@/lib/types/journal";
import { formatters, labelDataSource } from "@/lib/i18n/pt-br";

export function ReportsWorkspace({initialTrades,timeZone,source}:{initialTrades:TradeRecord[];timeZone:string;source:"DEMO"|"MANUAL"}) {
  const [trades,setTrades]=useState(initialTrades); useEffect(()=>{if(source!=="DEMO"){setTrades(initialTrades);return;}const local=loadDemoTrades();const ids=new Set(local.map(t=>t.id));setTrades([...local,...initialTrades.filter(t=>!ids.has(t.id))]);},[initialTrades,source]);
  const todayKey=localDateKey(new Date(),timeZone); const monthKey=currentMonthKey(timeZone); const today=useMemo(()=>buildDailyReport(trades,todayKey,timeZone),[trades,todayKey,timeZone]); const month=useMemo(()=>buildMonthlyReport(trades,monthKey,timeZone),[trades,monthKey,timeZone]);
  const monthTrades=useMemo(()=>trades.filter(t=>localDateKey(t.closedAt??t.openedAt,timeZone).startsWith(monthKey)),[trades,timeZone,monthKey]); const monthMetrics=useMemo(()=>calculatePerformanceMetrics(monthTrades),[monthTrades]); const dates=useMemo(()=>listAvailableDateKeys(trades,timeZone).slice(0,12),[trades,timeZone]);
  return <div className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-semibold tracking-tight text-slate-950">Relatórios</h1><p className="mt-1 text-sm text-slate-500">Resumo diário e mensal gerado diretamente do Journal.</p></div><div className="flex items-center gap-2"><StatusPill tone={source==="DEMO"?"info":"neutral"}><Database className="mr-1 size-3"/>{labelDataSource(source)}</StatusPill><Link href="/dashboard/calendar" className="action"><CalendarDays className="size-4"/>Calendário</Link></div></div>
    <section><div className="mb-3 flex items-center justify-between"><div><p className="eyebrow">Hoje</p><h2 className="mt-1 text-sm font-semibold text-slate-900">Resumo diário · {todayKey}</h2></div><Link href={`/dashboard/reports/${todayKey}`} className="inline-flex items-center gap-1 text-xs font-medium text-blue-600">Relatório completo <ArrowUpRight className="size-3"/></Link></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><ReportMetric label="P&L líquido" value={formatters.usd.format(today.netPnl)} tone={tone(today.netPnl)}/><ReportMetric label="Operações" value={String(today.tradeCount)} detail={`${today.openCount} em aberto`}/><ReportMetric label="Taxa de acerto" value={`${today.winRate.toFixed(1)}%`}/><ReportMetric label="Fator de lucro" value={today.profitFactor==null?"∞":today.profitFactor.toFixed(2)}/><ReportMetric label="Drawdown" value={formatters.usd.format(today.maxDrawdownPnl)} tone={today.maxDrawdownPnl>0?"negative":"neutral"}/><ReportMetric label="R médio" value={`${signed(today.averageR)}R`} tone={tone(today.averageR)}/></div></section>
    <section className="grid gap-4 xl:grid-cols-[1fr_1.4fr]"><div className="panel p-5"><p className="eyebrow">Mês atual</p><h2 className="mt-1 text-base font-semibold text-slate-900">{month.monthLabel}</h2><div className="mt-6 grid grid-cols-2 gap-x-8 gap-y-5"><Kpi label="P&L líquido" value={formatters.usd.format(monthMetrics.netPnl)} valueClass={toneClass(monthMetrics.netPnl)}/><Kpi label="Taxa de acerto" value={`${monthMetrics.winRatePct.toFixed(1)}%`}/><Kpi label="Fator de lucro" value={monthMetrics.profitFactor==null?"∞":monthMetrics.profitFactor.toFixed(2)}/><Kpi label="Lucro médio/op." value={formatters.usd.format(monthMetrics.expectancyPnl)} valueClass={toneClass(monthMetrics.expectancyPnl)}/><Kpi label="Drawdown máx." value={formatters.usd.format(monthMetrics.maxDrawdownPnl)} valueClass={monthMetrics.maxDrawdownPnl>0?"text-red-600":"text-slate-900"}/><Kpi label="Maior seq. perdas" value={String(monthMetrics.maxLossStreak)}/><Kpi label="Dias operados" value={String(month.activeDays)}/><Kpi label="Custos" value={formatters.usd.format(monthMetrics.totalFees)}/></div><Link href="/dashboard/performance" className="mt-6 inline-flex items-center gap-1 text-xs font-medium text-blue-600">Abrir análise de desempenho <ArrowUpRight className="size-3"/></Link></div>
      <div className="panel overflow-hidden"><div className="panel-header"><div><p className="eyebrow">Histórico</p><h2 className="mt-1 text-sm font-semibold text-slate-900">Dias recentes de operação</h2></div></div><div>{dates.map(dateKey=>{const report=buildDailyReport(trades,dateKey,timeZone);return <Link key={dateKey} href={`/dashboard/reports/${dateKey}`} className="grid grid-cols-[1fr_auto_auto] items-center gap-4 border-b border-slate-100 px-4 py-3 text-xs hover:bg-slate-50"><div><p className="font-medium text-slate-800">{dateKey}</p><p className="mt-0.5 text-[10px] text-slate-400">{report.tradeCount} operações · {report.wins}G {report.losses}P {report.breakEvens}BE</p></div><span className="tabular text-slate-500">{report.winRate.toFixed(0)}% acerto</span><span className={`tabular min-w-24 text-right ${toneClass(report.netPnl)}`}>{formatters.usd.format(report.netPnl)}</span></Link>})}{!dates.length?<p className="p-6 text-sm text-slate-400">Seus relatórios aparecerão depois que a primeira operação for registrada.</p>:null}</div></div></section>
  </div>;
}
function Kpi({label,value,valueClass="text-slate-900"}:{label:string;value:string;valueClass?:string}){return <div><p className="text-[10px] uppercase tracking-[0.12em] text-slate-400">{label}</p><p className={`tabular mt-1 text-lg font-semibold ${valueClass}`}>{value}</p></div>;} function signed(v:number){return `${v>=0?"+":""}${v.toFixed(2)}`;} function tone(v:number):"neutral"|"positive"|"negative"{return v>0?"positive":v<0?"negative":"neutral";} function toneClass(v:number){return v>0?"text-emerald-700":v<0?"text-red-600":"text-slate-500";}
