"use client";

import { useEffect, useMemo, useState, useTransition } from "react";
import { CheckCircle2, Search, ShieldAlert, UserCog } from "lucide-react";
import { StatusPill } from "@/components/ui/status-pill";
import type { AppRole } from "@/lib/auth/permissions";
import type { AdminAccountStatus, AdminAuditLog, AdminUser } from "@/lib/types/admin";
import { applyDemoRole, applyDemoStatus, loadDemoAdminLogs, loadDemoAdminUsers, makeDemoAuditLog, saveDemoAdminLogs, saveDemoAdminUsers } from "@/features/admin/data/demo-admin-store";
import { updateAdminUserRole, updateAdminUserStatus } from "@/features/admin/actions/admin-actions";

const roleLabel: Record<AppRole, string> = { FREE: "Gratuito", TRADER: "Trader", ADMIN: "Administrador" };
const roleTone = (role: AppRole): "accent" | "positive" | "neutral" => role === "ADMIN" ? "accent" : role === "TRADER" ? "positive" : "neutral";
const statusLabel: Record<AdminAccountStatus,string> = { PENDING: "Pendente", ACTIVE: "Ativo", SUSPENDED: "Suspenso" };
const statusTone = (status: AdminAccountStatus): "warning" | "positive" | "negative" => status === "PENDING" ? "warning" : status === "ACTIVE" ? "positive" : "negative";
function formatDate(value: string | null) { if (!value) return "Nunca"; return new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(value)); }

export function AdminUsersWorkspace({ initialUsers, initialLogs, demo, actorId }: { initialUsers: AdminUser[]; initialLogs: AdminAuditLog[]; demo: boolean; actorId: string }) {
  const [users, setUsers] = useState(initialUsers); const [logs, setLogs] = useState(initialLogs);
  const [query, setQuery] = useState(""); const [roleFilter, setRoleFilter] = useState<"ALL" | AppRole>("ALL"); const [statusFilter, setStatusFilter] = useState<"ALL" | AdminAccountStatus>("ALL");
  const [draftRoles, setDraftRoles] = useState<Record<string, AppRole>>({}); const [feedback, setFeedback] = useState<string | null>(null); const [isPending, startTransition] = useTransition();
  useEffect(() => { if (!demo) return; setUsers(loadDemoAdminUsers(initialUsers)); setLogs(loadDemoAdminLogs(initialLogs)); }, [demo, initialUsers, initialLogs]);
  const filtered = useMemo(() => users.filter((user) => { const term = query.trim().toLowerCase(); return (!term || `${user.displayName} ${user.email}`.toLowerCase().includes(term)) && (roleFilter === "ALL" || user.role === roleFilter) && (statusFilter === "ALL" || user.status === statusFilter); }), [users, query, roleFilter, statusFilter]);
  function commitDemo(usersNext: AdminUser[], logsNext: AdminAuditLog[]) { setUsers(usersNext); setLogs(logsNext); saveDemoAdminUsers(usersNext); saveDemoAdminLogs(logsNext); }
  function applyStatus(user: AdminUser, nextStatus: AdminAccountStatus, reason: string) { if (user.id === actorId && nextStatus !== "ACTIVE") { setFeedback("Você não pode bloquear sua própria conta administrativa."); return; } startTransition(async () => { const result = await updateAdminUserStatus(user.id, nextStatus, reason); if (!result.ok) { setFeedback(result.message); return; } if (demo) { const updated = applyDemoStatus(user, nextStatus); const usersNext = users.map((item) => item.id === user.id ? updated : item); const log = makeDemoAuditLog({ action: user.status === "PENDING" && nextStatus === "ACTIVE" ? "USER_APPROVED" : "USER_STATUS_CHANGED", target: user, metadata: { oldStatus: user.status, newStatus: nextStatus, reason } }); commitDemo(usersNext, [log, ...logs]); } else setUsers((current) => current.map((item) => item.id === user.id ? { ...item, status: nextStatus } : item)); setFeedback(nextStatus === "ACTIVE" ? `${user.displayName} está com acesso ativo.` : `${user.displayName} foi suspenso.`); }); }
  function changeRole(user: AdminUser) { const nextRole = draftRoles[user.id] ?? user.role; if (nextRole === user.role) return; if (user.id === actorId && nextRole !== "ADMIN") { setFeedback("Sua própria função de Administrador não pode ser removida."); return; } startTransition(async () => { const result = await updateAdminUserRole(user.id, nextRole); if (!result.ok) { setFeedback(result.message); return; } if (demo) { const updated = applyDemoRole(user, nextRole); const usersNext = users.map((item) => item.id === user.id ? updated : item); const log = makeDemoAuditLog({ action: "USER_ROLE_CHANGED", target: user, metadata: { oldRole: user.role, newRole: nextRole } }); commitDemo(usersNext, [log, ...logs]); } else setUsers((current) => current.map((item) => item.id === user.id ? { ...item, role: nextRole } : item)); setFeedback(`Função de ${user.displayName} atualizada para ${roleLabel[nextRole]}.`); }); }
  return <div className="space-y-5"><section><p className="eyebrow">Administração</p><h1 className="mt-1 text-2xl font-semibold text-slate-950">Usuários e liberações</h1><p className="mt-2 text-sm text-slate-500">Cadastros por e-mail/senha ou Google entram como pendentes. Você decide quem recebe acesso.</p></section>
    <section className="panel p-4"><div className="grid gap-3 lg:grid-cols-[minmax(280px,1fr)_180px_180px_auto]"><label className="relative"><Search className="absolute left-3 top-3 size-4 text-slate-400"/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Buscar por nome ou e-mail" className="h-10 w-full rounded-lg border border-slate-200 bg-white pl-9 pr-3 text-sm text-slate-700"/></label><select value={roleFilter} onChange={(e)=>setRoleFilter(e.target.value as "ALL"|AppRole)} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-600"><option value="ALL">Todas as funções</option><option value="FREE">Gratuito</option><option value="TRADER">Trader</option><option value="ADMIN">Administrador</option></select><select value={statusFilter} onChange={(e)=>setStatusFilter(e.target.value as "ALL"|AdminAccountStatus)} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-600"><option value="ALL">Todos os status</option><option value="PENDING">Pendentes</option><option value="ACTIVE">Ativos</option><option value="SUSPENDED">Suspensos</option></select><div className="flex items-center justify-end text-xs text-slate-400">{filtered.length} de {users.length}</div></div>{feedback ? <div className="mt-3 flex items-start gap-2 rounded-lg border border-blue-100 bg-blue-50 px-3 py-2 text-xs text-blue-700"><UserCog className="mt-0.5 size-4 shrink-0"/>{feedback}</div> : null}</section>
    <section className="panel overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[1160px] text-left text-sm"><thead className="border-b border-slate-100 bg-slate-50 text-[10px] uppercase tracking-[.12em] text-slate-400"><tr><th className="px-4 py-3">Usuário</th><th className="px-4 py-3">Função</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Último acesso</th><th className="px-4 py-3">Cadastro</th><th className="px-4 py-3">Acessos</th><th className="px-4 py-3">Administração</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((user)=><tr key={user.id} className="align-top hover:bg-slate-50"><td className="px-4 py-4"><p className="font-medium text-slate-900">{user.displayName}</p><p className="mt-1 text-xs text-slate-500">{user.email}</p></td><td className="px-4 py-4"><StatusPill tone={roleTone(user.role)}>{roleLabel[user.role]}</StatusPill></td><td className="px-4 py-4"><StatusPill tone={statusTone(user.status)}>{statusLabel[user.status]}</StatusPill></td><td className="px-4 py-4 text-xs text-slate-500">{formatDate(user.lastSignInAt)}</td><td className="px-4 py-4 text-xs text-slate-500">{formatDate(user.createdAt)}</td><td className="px-4 py-4"><span className="tabular font-semibold text-slate-700">{user.permissionCount}</span></td><td className="px-4 py-4"><div className="flex min-w-[290px] flex-col gap-2">{user.status === "PENDING" ? <button disabled={isPending} onClick={()=>applyStatus(user,"ACTIVE","Cadastro aprovado pelo administrador")} className="inline-flex h-8 items-center justify-center gap-2 rounded-lg bg-emerald-600 px-3 text-xs font-semibold text-white hover:bg-emerald-700 disabled:opacity-50"><CheckCircle2 className="size-3.5"/>Aprovar acesso</button> : null}<div className="flex gap-2"><select disabled={isPending} value={draftRoles[user.id] ?? user.role} onChange={(e)=>setDraftRoles((current)=>({...current,[user.id]:e.target.value as AppRole}))} className="h-8 flex-1 rounded-lg border border-slate-200 bg-white px-2 text-xs text-slate-600"><option value="FREE">Gratuito</option><option value="TRADER">Trader</option><option value="ADMIN">Administrador</option></select><button disabled={isPending || (draftRoles[user.id] ?? user.role) === user.role} onClick={()=>changeRole(user)} className="action">Aplicar</button></div>{user.status !== "PENDING" ? <button disabled={isPending || user.id === actorId} onClick={()=>user.status === "ACTIVE" ? applyStatus(user,"SUSPENDED","Suspensão administrativa") : applyStatus(user,"ACTIVE","Acesso reativado")} className="action justify-center">{user.status === "ACTIVE" ? "Suspender acesso" : "Reativar acesso"}</button> : null}</div></td></tr>)}{!filtered.length ? <tr><td colSpan={7} className="px-4 py-10 text-center text-sm text-slate-400">Nenhum usuário encontrado.</td></tr> : null}</tbody></table></div></section>
    <section className="flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-slate-600"><ShieldAlert className="mt-0.5 size-4 shrink-0 text-amber-600"/><p>Novos cadastros não recebem acesso aos dados da plataforma até a aprovação. A autorização real continua no servidor/banco, e não apenas na interface.</p></section>
  </div>;
}
