"use client";

import { useEffect, useMemo, useState } from "react";
import { BarChart3, FilterX, TrendingDown, TrendingUp } from "lucide-react";
import { buildPerformanceSnapshot } from "@/lib/core/performance-service";
import { DEFAULT_TRADE_FILTERS, filterTrades, type TradeFilterState } from "@/lib/core/trade-filter-service";
import type { TradeRecord } from "@/lib/types/journal";
import type { PerformanceBreakdownRow } from "@/lib/types/performance";
import { loadDemoTrades } from "@/features/journal/data/demo-trade-store";
import { formatters } from "@/lib/i18n/pt-br";
import { buildTradeTimelinePoints, getLastLosingTrade, getLastWinningTrade } from "@/lib/core/trade-insight-service";
import { InteractiveEquityCurve } from "@/components/charts/interactive-equity-curve";

type BreakdownKey = "strategy" | "asset" | "account" | "session" | "timeframe" | "tag";
const fieldClass = "h-9 rounded-lg border border-slate-200 bg-white px-3 text-xs text-slate-700";
function formatProfitFactor(value: number | null) { return value == null ? "∞" : value.toFixed(2); }
function mergeTrades(base: readonly TradeRecord[], stored: readonly TradeRecord[]) { const map = new Map<string,TradeRecord>(); for (const trade of [...stored,...base]) map.set(trade.id,trade); return [...map.values()]; }
function uniq(values:string[]){return [...new Set(values.filter(Boolean))].sort((a,b)=>a.localeCompare(b));}

export function PerformanceLab({ initialTrades, initialAccountId = "ALL" }: { initialTrades: TradeRecord[]; initialAccountId?: string }) {
  const [trades,setTrades]=useState(initialTrades); const [breakdown,setBreakdown]=useState<BreakdownKey>("asset");
  const [filters,setFilters]=useState<TradeFilterState>({...DEFAULT_TRADE_FILTERS,status:"CLOSED",accountId:initialAccountId});
  useEffect(()=>{ if(process.env.NEXT_PUBLIC_APP_MODE==="production"){ setTrades(initialTrades); return; } setTrades(current=>mergeTrades([...initialTrades,...current],loadDemoTrades())); },[initialTrades]);
  useEffect(()=>{ setFilters(current=>({...current,accountId:initialAccountId})); },[initialAccountId]);
  const symbols=useMemo(()=>uniq(trades.map(t=>t.symbol)),[trades]); const accounts=useMemo(()=>[...new Map(trades.map(t=>[t.accountId,t.accountName])).entries()],[trades]); const tags=useMemo(()=>uniq(trades.flatMap(t=>t.tags??[])),[trades]);
  const filtered=useMemo(()=>filterTrades(trades,filters),[trades,filters]); const snapshot=useMemo(()=>buildPerformanceSnapshot(filtered),[filtered]);
  const rows=useMemo(()=>breakdown==="strategy"?snapshot.byStrategy:breakdown==="account"?snapshot.byAccount:breakdown==="session"?snapshot.bySession:breakdown==="timeframe"?snapshot.byTimeframe:breakdown==="tag"?snapshot.byTag:snapshot.byAsset,[breakdown,snapshot]);
  const lastWin=useMemo(()=>getLastWinningTrade(filtered),[filtered]); const lastLoss=useMemo(()=>getLastLosingTrade(filtered),[filtered]); const timelinePoints=useMemo(()=>buildTradeTimelinePoints(filtered,"America/Sao_Paulo"),[filtered]);
  function patch<K extends keyof TradeFilterState>(key:K,value:TradeFilterState[K]){setFilters(current=>({...current,[key]:value}));}
  return <div className="space-y-4">
    <section className="panel p-3"><div className="flex flex-wrap items-center gap-2"><select className={fieldClass} value={filters.symbol} onChange={e=>patch("symbol",e.target.value)}><option value="ALL">Todos os ativos</option>{symbols.map(v=><option key={v}>{v}</option>)}</select><select className={fieldClass} value={filters.accountId} onChange={e=>patch("accountId",e.target.value)}><option value="ALL">Todas as contas</option>{accounts.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select><select className={fieldClass} value={filters.period} onChange={e=>patch("period",e.target.value as TradeFilterState["period"])}><option value="ALL">Todo período</option><option value="7D">1 semana</option><option value="14D">14 dias</option><option value="30D">1 mês</option><option value="90D">3 meses</option><option value="180D">6 meses</option><option value="365D">1 ano</option><option value="YTD">Ano atual</option><option value="CUSTOM">Personalizado</option></select><select className={fieldClass} value={filters.tag} onChange={e=>patch("tag",e.target.value)}><option value="ALL">Todas tags</option>{tags.map(tag=><option key={tag}>{tag}</option>)}</select>{filters.period==="CUSTOM"?<><input type="date" className={fieldClass} value={filters.fromDate} onChange={e=>patch("fromDate",e.target.value)}/><input type="date" className={fieldClass} value={filters.toDate} onChange={e=>patch("toDate",e.target.value)}/></>:null}<button className="action" onClick={()=>setFilters({...DEFAULT_TRADE_FILTERS,status:"CLOSED"})}><FilterX className="size-3.5"/>Limpar</button><span className="ml-auto text-xs text-slate-400">{snapshot.summary.trades} operações fechadas no recorte</span></div></section>

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="P&L líquido" value={formatters.usd.format(snapshot.summary.netPnl)} sub={`${snapshot.summary.trades} operações`} tone={snapshot.summary.netPnl>0?"positive":snapshot.summary.netPnl<0?"negative":"neutral"}/><Metric label="Taxa de acerto" value={`${snapshot.summary.winRatePct.toFixed(1)}%`} sub={`${snapshot.summary.wins} ganhos · ${snapshot.summary.losses} perdas`}/><Metric label="Último lucro" value={lastWin?.netPnl!=null?formatters.usd.format(lastWin.netPnl):"—"} sub={lastWin?`${lastWin.symbol} · ${formatDate(lastWin.closedAt ?? lastWin.openedAt)}`:"Sem ganho fechado"} tone={lastWin?"positive":"neutral"}/><Metric label="Última perda" value={lastLoss?.netPnl!=null?formatters.usd.format(lastLoss.netPnl):"—"} sub={lastLoss?`${lastLoss.symbol} · ${formatDate(lastLoss.closedAt ?? lastLoss.openedAt)}`:"Sem perda fechada"} tone={lastLoss?"negative":"neutral"}/></section>

    <div className="grid gap-4 2xl:grid-cols-[minmax(0,1.45fr)_minmax(340px,.55fr)]"><section className="panel overflow-hidden"><div className="panel-header"><div><p className="eyebrow">Curva de performance</p><h2 className="mt-1 text-sm font-semibold text-slate-900">P&L acumulado</h2><p className="mt-1 text-[10px] text-slate-400">Passe o mouse para ver datas, horas e resultados.</p></div></div><div className="p-4"><InteractiveEquityCurve points={timelinePoints} emptyText="Sem operações fechadas para desenhar a curva." /></div></section>
      <section className="panel overflow-hidden"><div className="panel-header"><div><p className="eyebrow">Métricas operacionais</p><h2 className="mt-1 text-sm font-semibold text-slate-900">Qualidade do histórico</h2></div><BarChart3 className="size-4 text-slate-400"/></div><div className="grid grid-cols-2 gap-3 p-4"><SmallMetric label="Ganho médio" value={formatters.usd.format(snapshot.summary.averageWinnerPnl)} icon="up" tone={snapshot.summary.averageWinnerPnl>0?"positive":"neutral"}/><SmallMetric label="Perda média" value={formatters.usd.format(snapshot.summary.averageLoserPnl)} icon="down" tone={snapshot.summary.averageLoserPnl<0?"negative":"neutral"}/><SmallMetric label="Expectância/op." value={formatters.usd.format(snapshot.summary.expectancyPnl)} tone={snapshot.summary.expectancyPnl>0?"positive":snapshot.summary.expectancyPnl<0?"negative":"neutral"}/><SmallMetric label="Custos totais" value={formatters.usd.format(snapshot.summary.totalFees)} tone={snapshot.summary.totalFees>0?"negative":"neutral"}/><SmallMetric label="Maior seq. ganhos" value={String(snapshot.summary.maxWinStreak)} tone={snapshot.summary.maxWinStreak>0?"positive":"neutral"}/><SmallMetric label="Maior seq. perdas" value={String(snapshot.summary.maxLossStreak)} tone={snapshot.summary.maxLossStreak>0?"negative":"neutral"}/></div></section></div>

    <section className="panel overflow-hidden"><div className="panel-header"><div><p className="eyebrow">Quebra de desempenho</p><h2 className="mt-1 text-sm font-semibold text-slate-900">Onde seu resultado se concentra</h2></div></div><div className="flex flex-wrap gap-2 border-b border-slate-100 p-3">{([ ["asset","Ativo"],["account","Conta"],["strategy","Estratégia"],["session","Sessão"],["timeframe","Timeframe"],["tag","Tags"] ] as const).map(([key,label])=><button key={key} type="button" onClick={()=>setBreakdown(key)} className={`rounded-lg border px-3 py-2 text-[10px] font-medium ${breakdown===key?"border-slate-900 bg-slate-900 text-white":"border-slate-200 bg-white text-slate-500 hover:bg-slate-50"}`}>{label}</button>)}</div><PerformanceTable rows={rows.slice(0,40)}/></section>
  </div>;
}
function PerformanceTable({rows}:{rows:PerformanceBreakdownRow[]}){return <div className="overflow-x-auto"><table className="min-w-[1050px] w-full text-left text-xs"><thead className="bg-slate-50 text-[9px] uppercase tracking-[0.12em] text-slate-400"><tr><th className="px-4 py-3">Grupo</th><th className="px-3 py-3">Operações</th><th className="px-3 py-3">Acerto</th><th className="px-3 py-3">P&L</th><th className="px-3 py-3">Média/op.</th><th className="px-3 py-3">Fator lucro</th><th className="px-3 py-3">DD máx.</th><th className="px-3 py-3">Seq. perdas</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.length?rows.map(row=><tr key={row.key} className="text-slate-600 hover:bg-slate-50"><td className="max-w-[280px] truncate px-4 py-3 font-medium text-slate-900">{row.label}</td><td className="tabular px-3 py-3">{row.trades}</td><td className="tabular px-3 py-3">{row.winRatePct.toFixed(1)}%</td><td className={`tabular px-3 py-3 ${row.netPnl>=0?"text-emerald-700":"text-red-600"}`}>{formatters.usd.format(row.netPnl)}</td><td className="tabular px-3 py-3">{formatters.usd.format(row.expectancyPnl)}</td><td className="tabular px-3 py-3">{formatProfitFactor(row.profitFactor)}</td><td className="tabular px-3 py-3">{formatters.usd.format(row.maxDrawdownPnl)}</td><td className="tabular px-3 py-3">{row.maxLossStreak}</td></tr>):<tr><td colSpan={8} className="px-4 py-8 text-center text-slate-400">Sem dados suficientes para esta análise.</td></tr>}</tbody></table></div>;}
function Metric({label,value,sub,tone="neutral"}:{label:string;value:string;sub:string;tone?:"neutral"|"positive"|"negative"}){const cls=tone==="positive"?"text-emerald-700":tone==="negative"?"text-red-600":"text-slate-950";return <div className="panel p-4 text-center"><p className={`tabular text-xl font-semibold ${cls}`}>{value}</p><p className="mt-2 text-[9px] font-semibold uppercase tracking-[0.12em] text-slate-400">{label}</p><p className="mt-1 text-[10px] text-slate-400">{sub}</p></div>;}
function SmallMetric({label,value,icon,tone="neutral"}:{label:string;value:string;icon?:"up"|"down";tone?:"neutral"|"positive"|"negative"}){const txt=tone==="positive"?"history-quality-positive text-emerald-700":tone==="negative"?"history-quality-negative text-red-600":"history-quality-neutral text-slate-500";const valueCls=tone==="positive"?"history-quality-positive text-emerald-700":tone==="negative"?"history-quality-negative text-red-600":"history-quality-neutral text-slate-900";return <div className="history-quality-card rounded-xl border border-slate-200 bg-white p-3 shadow-sm"><div className="flex items-center justify-between"><p className={`eyebrow ${txt}`}>{label}</p>{icon==="up"?<TrendingUp className="history-quality-positive size-3.5 text-emerald-600"/>:icon==="down"?<TrendingDown className="history-quality-negative size-3.5 text-red-500"/>:null}</div><p className={`tabular mt-1.5 text-sm font-semibold ${valueCls}`}>{value}</p></div>;}
function formatDate(value:string){return new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"2-digit",year:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(value));}
