import Link from "next/link";
import { ArrowRight, BarChart3 } from "lucide-react";
import type { MarketWatchItem } from "@/lib/types/trading";
import { labelBias, labelMarketType, labelStructure } from "@/lib/i18n/pt-br";
import { StatusPill } from "@/components/ui/status-pill";

const digits: Record<string, number> = { EURUSD: 5, GBPUSD: 5, USDJPY: 2, XAUUSD: 2, XAGUSD: 2, NAS100: 1, US30: 0, SPX500: 1, BTCUSD: 0, ETHUSD: 0 };

export function MarketUniverse({ items }: { items: MarketWatchItem[] }) {
  return <section className="panel overflow-hidden"><div className="panel-header"><div><p className="eyebrow">Universo operacional</p><h2 className="mt-1 text-sm font-semibold">Mercados monitorados</h2></div><StatusPill tone="info">Dados demonstrativos</StatusPill></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] border-collapse text-left text-xs"><thead><tr className="border-b border-slate-800 text-[9px] uppercase tracking-[0.14em] text-slate-600"><th className="px-4 py-2.5">Ativo</th><th>Mercado</th><th className="text-right">Preço</th><th className="text-right">Variação</th><th className="pl-5">Viés</th><th>Estrutura</th><th className="text-right">Contexto</th><th className="pr-4 text-right">Ação</th></tr></thead><tbody>{items.map((item) => <tr key={item.symbol} className="border-b border-slate-900/90 last:border-0 hover:bg-slate-900/35"><td className="px-4 py-3 font-semibold text-slate-200">{item.symbol}</td><td className="text-slate-500">{labelMarketType(item.market)}</td><td className="tabular text-right text-slate-300">{item.price.toLocaleString("pt-BR", { minimumFractionDigits: digits[item.symbol] ?? 2, maximumFractionDigits: digits[item.symbol] ?? 2 })}</td><td className={`tabular text-right ${item.changePct >= 0 ? "text-emerald-300" : "text-red-300"}`}>{item.changePct >= 0 ? "+" : ""}{item.changePct.toFixed(2)}%</td><td className="pl-5 text-slate-400">{labelBias(item.bias)}</td><td className="text-slate-400">{labelStructure(item.structure)}</td><td className="tabular text-right text-slate-400">{item.confluenceScore.value}/{item.confluenceScore.max}</td><td className="pr-4 text-right"><Link href={`/dashboard/analysis?symbol=${encodeURIComponent(item.symbol)}`} className="inline-flex items-center gap-1 text-sky-300 hover:text-sky-200"><BarChart3 className="size-3.5" />Analisar <ArrowRight className="size-3" /></Link></td></tr>)}</tbody></table></div></section>;
}
